language: python
python:
  - "2.7"
  
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
  - DJANGO_VERSION=1.9.0


# command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run tests
script: python manage.py test
